// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/produtos/:categoria?": {
    params: {
      "categoria"?: string;
    };
  };
  "/contato": {
    params: {};
  };
  "/sobre": {
    params: {};
  };
  "/suporte": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/produtos/:categoria?" | "/contato" | "/sobre" | "/suporte";
  };
  "routes/Home.tsx": {
    id: "routes/Home";
    page: "/";
  };
  "routes/Produtos.tsx": {
    id: "routes/Produtos";
    page: "/produtos/:categoria?";
  };
  "routes/Contato.tsx": {
    id: "routes/Contato";
    page: "/contato";
  };
  "routes/Sobre.tsx": {
    id: "routes/Sobre";
    page: "/sobre";
  };
  "routes/Suporte.tsx": {
    id: "routes/Suporte";
    page: "/suporte";
  };
};