// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/produtos": {
    params: {};
  };
  "/produtos/controle-acesso": {
    params: {};
  };
  "/produtos/relogio-ponto": {
    params: {};
  };
  "/produtos/sistemas": {
    params: {};
  };
  "/contato": {
    params: {};
  };
  "/sobre": {
    params: {};
  };
  "/suporte": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/produtos" | "/produtos/controle-acesso" | "/produtos/relogio-ponto" | "/produtos/sistemas" | "/contato" | "/sobre" | "/suporte";
  };
  "routes/Home.tsx": {
    id: "routes/Home";
    page: "/";
  };
  "routes/Produtos.tsx": {
    id: "routes/Produtos";
    page: "/produtos" | "/produtos/controle-acesso" | "/produtos/relogio-ponto" | "/produtos/sistemas";
  };
  "routes/produtos/ControleAcesso.tsx": {
    id: "routes/produtos/ControleAcesso";
    page: "/produtos/controle-acesso";
  };
  "routes/produtos/RelogioPonto.tsx": {
    id: "routes/produtos/RelogioPonto";
    page: "/produtos/relogio-ponto";
  };
  "routes/produtos/Sistemas.tsx": {
    id: "routes/produtos/Sistemas";
    page: "/produtos/sistemas";
  };
  "routes/Contato.tsx": {
    id: "routes/Contato";
    page: "/contato";
  };
  "routes/Sobre.tsx": {
    id: "routes/Sobre";
    page: "/sobre";
  };
  "routes/Suporte.tsx": {
    id: "routes/Suporte";
    page: "/suporte";
  };
};